title: ME-Well Lab
url: "https://www.me-well-lab.github.io"
baseurl: "https://www.me-well-lab.github.io"
tagline: xx
description: xx 

# seo-tag info
author:
  twitter: Xin_Tang_Finn
  name: Xin Tang
  image: /img/people/xintang.jpg
  url: https://www.me-well-lab.github.io/
twitter:
  username: Xin_Tang_Finn
  card: summary_large_image
social:
  name: Xin Tang
  links: 
    - https://twitter.com/Xin_Tang_Finn
    - https://orcid.org/0000-0002-0155-4967
    - https://scholar.google.com/citations?hl=en&user=mlBEMRYAAAAJ
    - https://www.researchgate.net/profile/Xin-Tang-25
locale: en_GB
logo: /img/logo.png

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for posts.
permalink: /:categories/:year/:month/:day/:title

# Number of news stories on the front page.
front_page_news: 5

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: 
        path: /img/logo.png
        alt: WYChow Lab logo


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- Makefile
- README.md
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
